name: Awesome Lint

on:
  push:
    paths:
      - README.md
      - .github/workflows/awesome-lint.yml
  pull_request:
    paths:
      - README.md
      - .github/workflows/awesome-lint.yml
  workflow_dispatch:

jobs:
  awesome-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install awesome-lint
        run: npm i awesome-lint

      - name: Lint README with awesome-lint
        run: npx awesome-lint README.md
